config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root "projects#index"
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_student!, only: [:new, :edit, :create, :update, :destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark navbar-static-top bg-dark">
    <div class="container-fluid text-white">
    <div class="col align-self-start"> <ul class="navbar-nav"><li class="nav-item active"><%= link_to "Home", root_path, :class => "nav-link" %></li></ul></div>
    <div class="col align-self-center text-center font-weight-bold">
        <% if Student.count > 0 %>
          <%= Student.find(1).name %>'s
        <% end %>
         Portfolio
    </div>
    <div class="col align-self-end text-right">
      <% if student_signed_in? %><%= button_to 'New Project', new_project_path, :method => :get, :class => "btn btn-success my-2 my-sm-0" %><% end %>
    </div>
    </div>
  </nav>

  <main role="main">


  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>
  <div>
  <%= yield %>
  </div>

</main>

    
    <nav class="navbar navbar-expand-md navbar-dark fixed-bottom bg-dark justify-content-center">
      <ul class="navbar-nav">
      <% if Student.count == 0 %>
        <li class="nav-item active"><%= link_to "Sign up", new_registration_path(Student), :class => "nav-link" %></li>
      <% elsif student_signed_in? %>
        <li class="nav-item active pr-5"><%= link_to "Sign Out", destroy_student_session_path, method: :delete, :class => "nav-link" %></li>
        <li class="nav-item"><%= link_to "Change Student", edit_registration_path(Student), :class => "nav-link" %></li>
      <% else %>
        <li class="nav-item active"><%= link_to "Sign in", new_session_path(Student), :class => "nav-link" %></li>
      <% end %>
      </ul>
    </nav>

  </body>
</html>

app/views/projects/_form.html.erb
<style>

.btn-login {
  font-size: 0.9rem;
  letter-spacing: 0.05rem;
  padding: 0.75rem 1rem;
}

</style>
  <% if project.errors.any? %>
    <div id="error_explanation" class="mx-auto">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card border-0 shadow rounded-3 my-5">
          <div class="card-body p-4 p-sm-5">
            <h5 class="card-title text-center mb-5 fw-light fs-5"><%= plabel %> Project</h5>
            <%= form_with(model: project, id:"primary", local: true) do |form| %>
              <div class="container">
                <div class="row mb-3">
                  <div class="col"><%= form.label :title %></div>
                  <div class="col"><%= form.text_field :title %></div>
                </div>
                <div class="row mb-3">
                  <div class="col"><%= form.label :description %></div>
                  <div class="col"><%= form.text_area :description %></div>
                </div>
              
              <hr class="my-2">
              <div class="actions d-grid text-center">
                <button class="btn btn-primary btn-login w-50 fw-bold" type="submit">Submit</button>
                <% end %>
                <%= button_to "Cancel", :back, :method => :get, :class => "btn btn-danger btn-login", form: {style: 'display:inline-block;'} %><br />
              </div>

          </div>
        </div>
      </div>
    </div>
  </div>

app/views/projects/edit.html.erb
<%= render 'form', project: @project, :plabel => "Edit" %>

app/views/projects/index.html.erb
<div class="container-fluid">
<div>
<% @projects.each_with_index do |project, index| %>
  <% if (index % 3) == 0 %>
  </div>
  <div class="row mb-4 justify-content-center">
  <% end %>
    <div class="col" style="width: 20%; max-width: 20em;">
      <div class="card h-100">
        <div class="card-body">
          <h2 class="card-title text-truncate"><%= project.title %></h2>
          <p class="card-text text-truncate"><%= project.description.html_safe %></p>
        </div>
      <div class="card-footer text-center"><%= button_to 'Show', project, :method => :get, :class => "btn btn-primary btn-sm mr-2 btn-block", form: {style: 'display:inline-block;'} %>  <% if student_signed_in? %><%= button_to 'Edit', edit_project_path(project), :method => :get, :class => "btn btn-secondary btn-sm mr-2 btn-block", form: {style: 'display:inline-block;'} %>
      <%= button_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm btn-block", form: {style: 'display:inline-block;'} %><% end %></div>
    </div>
    </div>
<% end %>
</div>

app/views/projects/new.html.erb
<%= render 'form', project: @project, :plabel => "New" %>

app/views/projects/show.html.erb
<div class ="container justify-content-center" >
<div class="col">
<div class="card h-100">
  <div class="card-body">
    <h2 class="card-title"><%= @project.title %></h2>
    <p class="card-text "><%= @project.description.html_safe %></p>
  </div>
<div class="card-footer text-center"> <%= button_to "Back", root_path, :method => :get, form: {style:"display: inline-block;"}, :class => "btn btn-primary btn-sm btn-block" %> <% if student_signed_in? %><%= button_to 'Edit', edit_project_path(@project), :method => :get, :class => "btn btn-secondary btn-sm mr-2 btn-block", form: {style: 'display:inline-block;'} %>
<%= button_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm btn-block", form: {style: 'display:inline-block;'} %><% end %></div>
</div>
</div>
</div>